# -*- coding: utf-8 -*-
"""Regresi Linier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FWDdYBo6jvub7QoZLK5uVZDBXE2uup8s
"""

import numpy as np
from sklearn.linear_model import LinearRegression

#Database
# x = Data, y = Target
x = [[5],[10],[15],[20],[25],[30],[35],[40],[45],[50]]
y = [15, 30, 45, 60, 75, 90, 105, 120, 135, 150]

regr = LinearRegression() .fit(x,y)
regr.score(x, y)



#Data uji
predict = np.array([[30]])

#Menampilkan data prediksi
print ("Prediksi")
print ("Input = ", predict)
print ("Outout = ", regr.predict(predict))