# -*- coding: utf-8 -*-
"""Regresi Polinomial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10awYn1PlsKuzgMKfL4C7w7JTzsKjQoPj
"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
import numpy as np

#Database
# x = Data, y = Target
x = [[2],[4],[6],[8],[10],[12],[14],[16],[18],[20]]
y = [4, 16, 36, 64, 100, 144, 196, 256, 324, 400]

#Data uji
predict = np.array([[22.5]])
poly = PolynomialFeatures(degree=2)
x_= poly.fit_transform(x)
predict = poly.fit_transform(predict)
regr = linear_model.LinearRegression()
regr.fit(x_,y)

#Menampilkan data prediksi
print ("Prediksi")
print ("Input = ", predict)
print ("Output = ", regr.predict(predict))